version: '3.9'

services:
  web-app:
    build: .
    restart: always
    container_name: niko-web
    working_dir: /app
    user: node
    ports:
      - '5173:5173'
    volumes:
      - .:/app
    environment:
      VITE_API_URL: http://localhost:3333
    command: yarn dev
